# -*- coding: utf-8 -*-
"""GuessTheNumber_2.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZ_vObkxT3aWknKGygtAuxFDQaILjlo2
"""

import random
import os

LEADERBOARD_FILE = '/content/leaderboard.txt'

def difficultyLevel():
  while True:
    try:
      choice = int(input("Choose difficulty:\n1. Easy (1-100)\n2. Medium (1-500)\n3. Hard (1-1000)\n"))

      match choice:
        case 1:
          print("Easy Mode selected (1-100)")
          return 1, 100
        case 2:
          print("Medium Mode selected (1-500)")
          return 1, 500
        case 3:
          print("Hard Mode selected (1-1000)")
          return 1, 1000
        case _: # Default case for invalid choice
          print("Invalid Choice. Please enter 1, 2, or 3.")

    except ValueError:
      print("Invalid input. Please enter a number corresponding to the difficulty.")

def guessTheNumber(min_val, max_val):
  random_number = random.randint(min_val, max_val) # Generate random number once
  print(f"I have picked a number between {min_val} and {max_val}. Can you guess it?")

  attempts = 0
  current_score = 0

  while True:
    attempts += 1 # Increment attempts for each guess
    try:
      user_guess = int(input("Enter your guess: "))

      if user_guess < min_val or user_guess > max_val:
        print(f"Your guess must be between {min_val} and {max_val}. Try again.")
        continue # Continue to next iteration if guess is out of range

      elif user_guess == random_number:
        if attempts == 1:
          current_score = 1000
        else:
          current_score = 1000 - (attempts * 2)
          if current_score < 0: # Ensure score doesn't go below 0
            current_score = 0
        # enterYourName is a global variable from the main execution scope
        print(f"Congratulations {enterYourName}! You guessed the correct number in {attempts} attempts! Your score is {current_score}.")
        return current_score # Return the score

      elif user_guess > random_number:
        print("Your guess is too high!")

      else:
        print("Your guess is too low!")

    except ValueError:
      print("Invalid input! Please enter an integer.")

def showLeaderboard(playerName, newScore):
    scores = []

    # Read existing scores
    try:
        with open(LEADERBOARD_FILE, "r") as file:
            for line in file:
                name, score_str = line.strip().split(",", 1) # Split only on the first comma
                scores.append((name, int(score_str)))
    except FileNotFoundError:
        pass # File doesn't exist yet, which is fine
    except Exception as e:
        print(f"An error occurred while reading leaderboard: {e}")

    # Add the current player's score
    scores.append((playerName, newScore))

    # Sort scores in descending order
    scores.sort(key=lambda x: x[1], reverse=True)

    # Write all scores back to the file (overwriting it)
    try:
        with open(LEADERBOARD_FILE, "w") as file:
            for name, score in scores:
                file.write(f"{name},{score}\n")
    except Exception as e:
        print(f"An error occurred while writing to leaderboard: {e}")

    print("\n🏆 LEADERBOARD 🏆")
    for rank, (name, score) in enumerate(scores[:5], start=1): # Display top 5 scores
        print(f"{rank}. {name} - {score}")
    print("------------------")

# Main execution
enterYourName = input("Enter your name: ")
print(f"Hello, {enterYourName}! Welcome to the Number Guessing Game!")

while True:
  min_range, max_range = difficultyLevel()
  final_score = guessTheNumber(min_range, max_range) # Get the score
  if final_score is not None: # Only update leaderboard if a game was completed successfully
    showLeaderboard(enterYourName, final_score)

  # Loop to handle 'play again' input validation
  while True:
    playAgain = input("Do you want to play again? (y/n): ").lower()
    if playAgain in ('y', 'n'):
      break
    else:
      print("Invalid input. Please enter 'y' or 'n'.")

  if playAgain != "y":
    break

print("Thanks for playing!")

